### PR TITLE
Added Ropsten Registry address to the Json

### PR DESCRIPTION
**Pull request by anandrgitnirman**
~~Changed the version to 2.0.1~~
Added Ropsten Registry address to the Json

### CODE REVIEW

**Comment by anandrgitnirman** [comment]
@tiero @raamb @stellarspot  request your review and approval on thisi pull request

**Comment by ksridharbabuus** [comment]
I agree on not to increase the version number at least for token contracts

**Comment by anandrgitnirman** [comment]
@ksridharbabuus @tiero  have reverted back the version 
@astroseger  , we will not need to change the version of token contract to 2.0.1 as previously thought

**Comment by astroseger** [comment]
Will it be possible to update NPM package without version update ?

**Pull request merged**
